# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Convidado',
        ),
    ]
