# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convidado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convidado',
            name='confirma_presenca',
            field=models.BooleanField(default=True, verbose_name='Confirma presença'),
        ),
        migrations.AddField(
            model_name='convidado',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='convidado',
            name='nome_convidado',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
