# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convidado', '0005_listaconvidados'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaconvidados',
            name='convidado_por',
            field=models.CharField(choices=[('NO', 'Noivo'), ('NA', 'Noiva')], default='NO', max_length=2, verbose_name='Convidado por'),
            preserve_default=False,
        ),
    ]
